# -*- coding: utf-8 -*-
"""Day4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19WdkwOjY_GNqCaMNnGcst5Hk166bcRFz
"""



"""##Day4 python

## First Exercise
"""



"""when we want to access index negative even if it was out of range you will get the whole container /not with slicing with indexing

None same thing as when want to reach the last element
"""

name="Johnson"
print(name[0])
print(name[1])
print(name[-1])
print(name[-2])

"""[start:end:step] in slicing  if the step in negative in the opposite direction

"""

name="Johnson"
print(name[::2])
print(name[::-1])
print(name[1:5:2])
print(name[-5:-2:1])

Academy="Tuwaiq"
print(Academy[::-1])

Academy="school"
print(Academy[1::2])

Team="Alhilal"
Team=Team.upper()
print(Team[::-2])

greeting="Hello world"
print(greeting.count("o"))



"""Exercise 2

formation of strings  we have 3 methods
"""

first_name="Abdulrahman"
last_name="Almadi"
print("your name is "+first_name+" "+last_name)
print("your name is {} {}".format(first_name,last_name))
print(f"your name is {first_name} {last_name}")

first_name="abdulrhman"
last_name="almadi"
age=21
print(f"Hello, My name is {first_name.capitalize()} {last_name.capitalize()}. and I'm {age} years old. ")

num=10.5679
print(type(num))

print("{:.3f}".format(num))

print(f"{num:.3f}")

print(f"{num:>100.2f}")

len('
                                                                                               10.57')

big_num=1000000
print(f"{big_num:,}")





mixed_List=["Car",123,50.43,True,["harry potter","michael Jackson","Ronaldo"]]
print(mixed_List[4][1][14])
print(mixed_List[4][::-1])
mixed_List[4][-1]



Favorite_Movies=["F1","OPENHIEMER","NOW YOU SEE ME 3 "]
for i in Favorite_Movies:
  print(i)

Negative_words=["Sad","angry","frustrated","disappointed","terrible","awful"]
print(Negative_words[1])
print(Negative_words[-1])
print(Negative_words[-3])

Negative_three_words=[]
for i in Negative_words[0:3] :
 Negative_three_words.append(i)
print(Negative_three_words)

List_start_to_end=[]
for i in Negative_words[1:5]:
  List_start_to_end.append(i)
print(List_start_to_end)

List_1=[]
for i in Negative_words[::2]:
  List_1.append(i)
print(List_1)

Negative_words=["Sad","angry","frustrated","disappointed","terrible","awful"]
print("awful" in Negative_words)
print("happy" in Negative_Words)
index=Negative_words.index("furstrated")
print(index)

list_1=[1,2,3]

for i in range(len(list_1)):
  if i%2==0:
    list_1[i]=list_1[i]+10
  elif i%2==1:
    list_1[i]=list_1[i]*list_1[i-1]
  else:
    print("number doesn't exist")
print(list_1)

new_list=enumerate(list_1)
print(list(new_list))





