# -*- coding: utf-8 -*-
"""Homework_Day3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/124kEW_k5AmpYUgQ5-UpN2e625fI2vuTt
"""

temperature_in_celsius=int(input("Enter the temperature in celsius: "))
temperature_in_fahrenheit=9/5*(temperature_in_celsius)+32
print("The temperature in Fahrenheit in your current place is =",temperature_in_fahrenheit)